export enum Thema {
	Arbeit = 'Arbeit',
	Außenpolitik = 'Außenpolitik',
	Bildung = 'Bildung',
	BudgetUndFinanzen = 'Budget und Finanzen',
	EuropäischeUnion = 'Europäische Union',
	FamilieUndGenerationen = 'Familie und Generationen',
	FrauenUndGleichbehandlung = 'Frauen und Gleichbehandlung',
	GesundheitUndErnährung = 'Gesundheit und Ernährung',
	InformationUndMedien = 'Information und Medien',
	InneresUndRecht = 'Inneres und Recht',
	InnovationTechnologieUndForschung = 'Innovation, Technologie und Forschung',
	KlimaUmweltUndEnergie = 'Klima, Umwelt und Energie',
	Kultur = 'Kultur',
	LandUndForstwirtschaft = 'Land- und Forstwirtschaft',
	Landesverteidigung = 'Landesverteidigung',
	ParlamentUndDemokratie = 'Parlament und Demokratie',
	Soziales = 'Soziales',
	Sport = 'Sport',
	VerkehrUndInfrastruktur = 'Verkehr und Infrastruktur',
	Wirtschaft = 'Wirtschaft',
}

export enum Gremium {
	Nationalrat = 'NR',
	Bundesrat = 'BR',
}

export enum Gegenstand {
	Aktuelle_Europastunden = 'ASEU',
	Aktuelle_Stunden = 'AS',
	Anfragen = 'J_JPR_M',
	Antraege = 'ANTR',
	Antraege_Untersuchungsauschuss = 'US',
	Ausschussberichte = 'AUB',
	Beantwortungen = 'AB_ABPR_ABM',
	Berichte_an_den_Nationalrat = 'III',
	Beschluesse = 'BNR',
	Buergerinitiativen = 'BI',
	Einsprueche_des_Bundesrats = 'EBR',
	Entschliessungen = 'E',
	EU_Vorlagen_Beschluesse = 'EU',
	Geschaeftsbehandlungen = 'GO',
	Gesetzesanträge_des_Bundesrates = 'GABR',
	Gesetzesantraege_von_einem_Drittel_des_BR = 'GABR13',
	Immunitätsangelegenheiten = 'IMM',
	Kommuniques = 'KOMM',
	Petitionen = 'PET',
	Regierungserklärungen = 'RGER',
	Regierungsvorlagen_Gesetze = 'RV',
	Staatsverträge = 'RVS',
	Trauerkundgebungen = 'TRAU',
	Vereinbarungen_gemaess_art15aB_VG = 'RVS15',
	Volksbegehren = 'VOLKBG',
	Wahlen = 'W',
}

export enum AntragsArtNationalrat {
	SelbständigerAntrag = 'A',
	SelbständigerEntschließungsantrag = 'A(E)',
	Abänderungsantrag = 'AA',
	SelbständigerAusschussEntschließungsantrag = 'AEA',
	SelbständigerAntragMinisteranklage = 'AMIN',
	VerlangenAufGebarungsüberprüfungRechnungshof = 'ARH2',
	AntragAufVolksbefragung = 'AVB',
	BerichtUndAntrag = 'BUA',
	UnselbständigerEntschließungsantrag = 'UEA',
	Misstrauensantrag = 'MEA',
	VerlangenAufGebarungsüberprüfungStändigerUARechnungshofausschuss = 'URH2',
}

export enum AntragsArtBundesrat {
	Abänderungsanträge = 'AA-BR',
	SelbständigerAntragBundesrat = 'A-BR',
	SelbständigerEntschließungsantragBundesrat = 'A(E)',
	SelbständigeEntschließungsanträgeVonAusschüssen = 'AEA-BR',
	UnselbständigeAnträge = 'UEA-BR',
}

export enum Fraktion {
	FPÖ = 'F',
	GRÜNE = 'G',
	ÖVP = 'V',
	NEOS = 'N',
	OK = 'A',
	SPÖ = 'S',
	JETZT = 'J',
	PILZ = 'P',
}

export enum Gesetzgebungsperiode {
	XXVII_2019 = 'XXVII',
	XXVI_2017_2019 = 'XXVI',
	XXV_2013_2017 = 'XXV',
	XXIV_2008_2013 = 'XXIV',
	XXIII_2006_2008 = 'XXIII',
	XXII_2002_2006 = 'XXII',
	XXI_1999_2002 = 'XXI',
	XX_1996_1999 = 'XX',
	XIX_1994_1996 = 'XIX',
	XCIII_1990_1994 = 'XCIII',
	XVII_1986_1990 = 'XVII',
	XVI_1983_1986 = 'XVI',
	XV_1979_1983 = 'XV',
	XIV_1975_1979 = 'XIV',
	XIII_1971_1975 = 'XIII',
	XII_1970_1971 = 'XII',
	XI_1966_1970 = 'XI',
	X_1962_1966 = 'X',
	IX_1959_1962 = 'IX',
	VIII_1956_1959 = 'VIII',
	VII_1953_1956 = 'VII',
	VI_1949_1953 = 'VI',
	V_1945_1949 = 'V',
	IV_1930_1934 = 'IV',
	III_1927_1930 = 'III',
	II_1923_1927 = 'II',
	I_1920_1923 = 'I',
	Konstituierende_Nationalratsversammlung = 'KN',
	Provisorische_Nationalratsversammlung = 'PN',
}
