import { HttpInterceptorFn, HttpResponse } from '@angular/common/http';
import { of } from 'rxjs';
import { fpö_grüne_arbeit } from '../api/mock/fpö_grüne_arbeit';

export const apiInterceptor: HttpInterceptorFn = (request, next) => {
	/* 	if (request.url.includes('/api/filter/') && request.method === 'POST') {
		return of(
			new HttpResponse({
				status: 200,
				body: {
					rows: fpö_grüne_arbeit,
					count: fpö_grüne_arbeit.length,
					header: [
						{
							hidden: true,
							rnr: 1,
							listeId: 101,
							label: 'GP_CODE',
							feld_name: 'GP',
						},
						{
							hidden: true,
							rnr: 2,
							listeId: 101,
							label: 'ITYP',
							feld_name: 'ITYP',
						},
						{
							hidden: true,
							rnr: 3,
							listeId: 101,
							label: 'INR',
							feld_name: 'INR',
						},
						{
							hidden: true,
							rnr: 4,
							listeId: 101,
							label: 'ZUKZ',
							feld_name: 'ZUKZ',
						},
						{
							css_class: 'datum-col',
							filterable: '1',
							hidden: false,
							sort_rnr: 17,
							rnr: 5,
							display_rnr: 1,
							listeId: 101,
							mediaType: 'datetime',
							label: 'Datum',
							sortable: '1',
							feld_name: 'DATUM',
							class: 'datum-col',
						},
						{
							tooltip_rnr: 14,
							css_class: 'stellungnahmen-col',
							hidden: false,
							rnr: 6,
							listeId: 101,
							mediaType: 'type',
							label: 'Art',
							sortable: '1',
							feld_name: 'ART',
							class: 'stellungnahmen-col',
						},
						{
							link_rnr: '15',
							hidden: false,
							rnr: 7,
							display_rnr: 2,
							listeId: 101,
							mediaType: 'title',
							label: 'Betreff',
							sortable: '1',
							feld_name: 'PFAD',
						},
						{
							css_class: 'datum-col',
							hidden: false,
							sort_rnr: 28,
							rnr: 8,
							listeId: 101,
							mediaType: 'description',
							label: 'Nummer',
							sortable: '1',
							feld_name: 'ZITATION',
							class: 'datum-col',
						},
						{
							hidden: true,
							rnr: 9,
							listeId: 101,
							label: 'DATUMSORT',
							feld_name: 'DATUMSORT',
						},
						{
							hidden: true,
							rnr: 10,
							listeId: 101,
							label: 'PHASEN_BIS',
							feld_name: 'PHASEN_BIS',
						},
						{
							css_class: 'status-col',
							hidden: false,
							rnr: 11,
							listeId: 101,
							mediaType: 'status',
							label: 'Status',
							sortable: '1',
							feld_name: 'STATUS',
							class: 'status-col',
						},
						{
							hidden: true,
							rnr: 12,
							listeId: 101,
							label: 'DOKTYP',
							feld_name: 'DOKTYP',
						},
						{
							hidden: true,
							rnr: 13,
							listeId: 101,
							label: 'Zust?',
							feld_name: 'ZZZZ',
						},
						{
							hidden: true,
							rnr: 14,
							listeId: 101,
							label: 'DOKTYP_LANG',
							feld_name: 'DOKTYP_LANG',
						},
						{
							hidden: true,
							rnr: 15,
							listeId: 101,
							mediaType: 'link',
							label: 'HIS_URL',
							feld_name: 'HIS_URL',
						},
						{
							hidden: true,
							rnr: 16,
							listeId: 101,
							label: 'RSS_DESC',
							feld_name: 'RSS_DESC',
						},
						{
							ist_range: '1',
							hidden: true,
							rnr: 17,
							icon: 'CHALKBOARD_TEACHER',
							listeId: 101,
							mediaType: 'fromDate',
							label: 'DATUM_VON',
							feld_name: 'DATUM_VON',
						},
						{
							hidden: true,
							rnr: 18,
							listeId: 101,
							label: 'VHG',
							feld_name: 'VHG',
						},
						{
							hidden: true,
							rnr: 19,
							listeId: 101,
							label: 'VHG2',
							feld_name: 'VHG2',
						},
						{
							hidden: true,
							rnr: 20,
							listeId: 101,
							label: 'LZ-Buttons',
						},
						{
							hidden: true,
							rnr: 21,
							display_rnr: 6,
							listeId: 101,
							label: 'Personen',
							feld_name: 'PAD_INTERN',
							ist_werteliste: '1',
						},
						{
							hidden: true,
							rnr: 22,
							listeId: 101,
							label: 'Fraktionen',
							feld_name: 'FRAK_CODE',
							ist_werteliste: '1',
						},
						{
							hidden: true,
							rnr: 23,
							listeId: 101,
							label: 'THEMEN',
							feld_name: 'THEMEN',
							ist_werteliste: '1',
						},
						{
							hidden: true,
							rnr: 24,
							listeId: 101,
							label: 'SW',
							feld_name: 'SW',
							ist_werteliste: '1',
						},
						{
							hidden: true,
							rnr: 25,
							listeId: 101,
							label: 'EUROVOC',
							feld_name: 'EUROVOC',
							ist_werteliste: '1',
						},
						{
							hidden: true,
							rnr: 26,
							listeId: 101,
							label: 'sysdate???',
						},
						{
							hidden: true,
							rnr: 27,
							listeId: 101,
							label: 'WENTRY_ID',
							ist_web_item_id: '1',
						},
						{
							ist_range: '1',
							hidden: true,
							rnr: 28,
							listeId: 101,
							mediaType: 'number',
							label: 'INRNUM',
							feld_name: 'INRNUM',
						},
						{
							hidden: true,
							rnr: 29,
							listeId: 101,
							label: 'NR_GP_CODE',
							feld_name: 'GP_CODE',
						},
						{
							hidden: true,
							rnr: 30,
							listeId: 101,
							label: 'NRBR',
							feld_name: 'NRBR',
						},
					],
				},
			})
		);
	} */
	return next(request);
};
